version: '3.8'

services:
  messenger-ai-backend:
    build: .
    ports:
      - "8000:8000"
      - "8765:8765"
    environment:
      - GOOGLE_PROJECT_ID=${GOOGLE_PROJECT_ID}
      - GOOGLE_APPLICATION_CREDENTIALS=/app/credentials.json
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - VERTEX_LOCATION=${VERTEX_LOCATION}
    volumes:
      - ./credentials.json:/app/credentials.json:ro
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Add a reverse proxy for production
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - messenger-ai-backend
    restart: unless-stopped
